# Text Analysis

In [2]:
import tensorflow

# The two datasets

In [5]:
import pandas as pd

In [31]:
covid = pd.read_csv('NATIONALforNLP.csv')

In [8]:
covid.head()

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,totale_casi,tamponi,casi_testati,nuovi_tamponi,nuovi_casi_testati,nuovi_deceduti
0,2020-02-24,101,26,127,94,221,0,221,1,7,229,4324,0.0,4324,0.0,7
1,2020-02-25,114,35,150,162,311,90,93,1,10,322,8623,0.0,4299,0.0,3
2,2020-02-26,128,36,164,221,385,74,78,3,12,400,9587,0.0,964,0.0,2
3,2020-02-27,248,56,304,284,588,203,250,45,17,650,12014,0.0,2427,0.0,5
4,2020-02-28,345,64,409,412,821,233,238,46,21,888,15695,0.0,3681,0.0,4

In [19]:
import os
print(os.getcwd())

C:\Users\leona\Desktop\Covid

In [38]:
reddit1 = pd.read_csv("RedditData/Comments_Data_1.csv", sep = "\t", encoding = "utf-8", index_col = 0)

In [39]:
reddit1

,Author,Submission ID,Text,Hour,Minute,Second,ID,Top Level,Parent ID,#Upvotes
0,Lord_TheJc,f7txjb,"Chiudo il thread, andate su quello nuovo\n\n/r...",12,25,40,fijqzau,True,f7txjb,1
1,EMOSCAMBIO,f7txjb,>Ore 19.30 - Il presunto «paziente 0» negativo...,18,52,58,figab7t,True,f7txjb,83
2,drstins_n,f7txjb,> Si allontana da Codogno e torna ad Avellino:...,21,40,54,fih8gxg,True,f7txjb,77
3,IceTea666,f7txjb,Dogana slovenia/croazia. Il poliziotto croato ...,22,17,8,fihft9k,True,f7txjb,75
4,panoramegamix,f7txjb,ho dato una veloce occhiata sui social \n\nNor...,17,52,2,fifwfbh,True,f7txjb,122
...,...,...,...,...,...,...,...,...,...,...
23019,Nico777,fc6a3o,"Certo, era puramente teorico il mio ragionamento.",20,58,23,fjaxwgc,False,fjaxkyj,2
23020,Mululu86,fc6a3o,Parlare con lei è davvero tempo sprecato. Buon...,10,52,14,fj9fmi3,False,fj9fh3o,0
23021,JonhC,fc6a3o,Difficile accettare quando un sbaglia eh?,10,53,7,fj9fnzi,False,fj9fmi3,1
23022,Mululu86,fc6a3o,Spero tu stia trollando,10,54,4,fj9fpml,False,fj9fnzi,0
23023,JonhC,fc6a3o,In realtà spero che tu lo sa\n\nUn video dalla...,10,57,9,fj9fuvh,False,fj9fpml,1

In [40]:
reddit1.columns

Index(['Author', 'Submission ID', 'Text', 'Hour', 'Minute', 'Second', 'ID',
       'Top Level', 'Parent ID', '#Upvotes'],
      dtype='object')

# Process to add the date to Megathreads

In [41]:
Megathreads = pd.read_csv("RedditData/Megathreads_Data.csv", sep = "\t", encoding = "utf-8", index_col = 0)

In [42]:
Megathreads

,ID,Month,Day,Title,#Upvotes,#Comments,Upvote Ratio
0,f7txjb,2,22,[MegaThread #3] CoronaVirus,392,2238,0.97
1,f87rbo,2,23,[MegaThread #4] CoronaVirus,272,3526,0.97
2,f8n5re,2,24,[MegaThread #5] CoronaVirus,339,3905,0.98
3,f979ky,2,25,[MegaThread #6] CoronaVirus,287,3209,0.97
4,f9ppti,2,26,[MegaThread #7] CoronaVirus,143,2630,0.96
...,...,...,...,...,...,...,...
73,gex2s7,5,7,Megathread Coronavirus * 07/05/20,122,496,0.99
74,gfjrni,5,8,Megathread Coronavirus * 08/05/20,112,578,0.96
75,gg5yq6,5,9,Megathread Coronavirus * 09/05/20,75,296,0.96
76,ggqrld,5,10,Megathread Coronavirus * 10/05/20,60,312,0.86
77,ghe13x,5,11,Megathread Coronavirus * 11/05/20,65,238,0.91

In [51]:
Megathreads['Date']= (Megathreads['Day']).astype(str)+'-'+(Megathreads['Month']).astype(str)+'-2020'

In [52]:
Megathreads

,ID,Month,Day,Title,#Upvotes,#Comments,Upvote Ratio,Date
0,f7txjb,2,22,[MegaThread #3] CoronaVirus,392,2238,0.97,22-2-2020
1,f87rbo,2,23,[MegaThread #4] CoronaVirus,272,3526,0.97,23-2-2020
2,f8n5re,2,24,[MegaThread #5] CoronaVirus,339,3905,0.98,24-2-2020
3,f979ky,2,25,[MegaThread #6] CoronaVirus,287,3209,0.97,25-2-2020
4,f9ppti,2,26,[MegaThread #7] CoronaVirus,143,2630,0.96,26-2-2020
...,...,...,...,...,...,...,...,...
73,gex2s7,5,7,Megathread Coronavirus * 07/05/20,122,496,0.99,7-5-2020
74,gfjrni,5,8,Megathread Coronavirus * 08/05/20,112,578,0.96,8-5-2020
75,gg5yq6,5,9,Megathread Coronavirus * 09/05/20,75,296,0.96,9-5-2020
76,ggqrld,5,10,Megathread Coronavirus * 10/05/20,60,312,0.86,10-5-2020
77,ghe13x,5,11,Megathread Coronavirus * 11/05/20,65,238,0.91,11-5-2020

In [53]:
Megathreads.to_csv('MegaThWithDate.csv', index = False)

# Dict creation thread:date, so we can add column date to the ReddtiData comments

In [65]:
def dictcreat(data):
    thdat = {}
    for index, row in data.iterrows():
        thdat[row['ID']]= row['Date']
    return thdat

In [66]:
thdat = dictcreat(Megathreads)

# Now I add the column to the Comments

In [133]:
l = [1,2,3,4,5,6,7,8]

In [136]:
def adderDate(listofcsv, dic):
    for i in listofcsv:
        doc = pd.read_csv('RedditData/Comments_Data_'+str(i)+'.csv', sep = "\t", encoding = "utf-8", index_col = 0)
        temp = doc
        doc['DATE'] = '0'
        for index, row in temp.iterrows():
            doc.set_value(index, 'DATE', dic[row['Submission ID']]) 
        doc.to_csv('RedditData/NewComments_Data'+str(i)+'.csv', index = False )
    return

In [137]:
adderDate(l, thdat)

C:\Users\leona\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys

In [140]:
newreddit1 = pd.read_csv("RedditData/NewComments_Data1.csv")#, sep = "\t", encoding = "utf-8", index_col = 0)
newreddit1.head()

,Author,Submission ID,Text,Hour,Minute,Second,ID,Top Level,Parent ID,#Upvotes,DATE
0,Lord_TheJc,f7txjb,"Chiudo il thread, andate su quello nuovo\n\n/r...",12,25,40,fijqzau,True,f7txjb,1,22-2-2020
1,EMOSCAMBIO,f7txjb,>Ore 19.30 - Il presunto «paziente 0» negativo...,18,52,58,figab7t,True,f7txjb,83,22-2-2020
2,drstins_n,f7txjb,> Si allontana da Codogno e torna ad Avellino:...,21,40,54,fih8gxg,True,f7txjb,77,22-2-2020
3,IceTea666,f7txjb,Dogana slovenia/croazia. Il poliziotto croato ...,22,17,8,fihft9k,True,f7txjb,75,22-2-2020
4,panoramegamix,f7txjb,ho dato una veloce occhiata sui social \n\nNor...,17,52,2,fifwfbh,True,f7txjb,122,22-2-2020